### ISSUE TITLE
[Editorial] Example 32 has a non functioning button

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#842]
The button to show or hide the default bindings on [Example 32](https://www.w3.org/TR/wot-thing-description/#example-32) is not working, i.e. nothing happens when pressed.

**Comment by sebastiankb** [comment]
there seems a different behavior of the https://www.w3.org/TR/wot-thing-description/#example-32 and https://w3c.github.io/wot-thing-description/#example-32 
There seems a probleme with the line
`document.respecIsReady.then(() => {`

In my understanding, respec should be not available when the spec is published at w3.org, right? 

@ashimura  can you check this issue?

**Comment by ashimura** [comment]
You're right. Respec is not available for the published draft on the W3C server.

**Comment by sebastiankb** [comment]
we should check if all other examples are working after the fix (example 3 & example 32).

the TD ontologies has the same feature. 
https://www.w3.org/2019/wot/td  (will work when the PR from Victor will be merged)
We should also check if the feature is working.

**Comment by vcharpenay** [comment]
on a static page, the promise callback should be put inside the following event listener:

```js
document.addEventListener('readystatechange', () => {
  if (document.readyState === 'complete') {
    // code here
  }
});
```

**Comment by danielpeintner** [comment]
to avoid issues in the future ...

Can the code above not also work for the editors version?
I assume `'complete'` also applies to respec?

Might be worthwhile checking...

**Comment by ashimura** [comment]
I've generated a static version HTML for Proposed REC publication at:
  https://w3c.github.io/wot-thing-description/publication/pr/index.html
and applied @vcharpenay 's suggested change above, but it seems example 32 doesn't work properly.

We need further investigation, don't we?

**Comment by mmccool** [comment]
Kaz and I discussed this and we will handle it during the publication process.  It's basically a bug and needs to be addressed by W3C and be fixed in e.g. the Preview mechanism.

**Comment by danielpeintner** [comment]
the code snippet brackets are broken... there is an unnecessary `);` in the pre-last line... the full code should be like this... 

```
 document.addEventListener('readystatechange', () => {
        if (document.readyState === 'complete') {
            document.querySelectorAll('.with-default').forEach(n => {
                let wo = n.querySelector('pre:nth-of-type(1)');
                let w = n.querySelector('pre:nth-of-type(2)');
                let cbox = n.querySelector('.with-default-control input[type="checkbox"]');

                w.classList.add('selected');
                cbox.checked = true;

                cbox.addEventListener('change', e => {
                    if (e.target.checked) {
                        // with default
                        w.classList.add('selected');
                        wo.classList.remove('selected');
                    } else {
                        // without
                        w.classList.remove('selected');
                        wo.classList.add('selected');
                    }
                });
            });
        } // XXXXX HERE was the error
    });
```

**Comment by ashimura** [comment]
Thanks a lot, @danielpeintner !

I've fixed the JS snippet and it seems the checkbox at the example 32 is working now:
  https://w3c.github.io/wot-thing-description/publication/pr/index.html#example-32 :)

**Comment by takuki** [comment]
In 2/28 TD call, Kaz suggested to keep this issue open till we publish Recommendation.

**Comment by egekorkan** [comment]
In the Recommendation, this seems to be fixed. Propose closing

**Comment by danielpeintner** [comment]
> In the Recommendation, this seems to be fixed. Propose closing

The issue still exists in the working branch (see [line](https://github.com/w3c/wot-thing-description/blob/master/index.template.html#L248) which still has the unneeded `);`)

**Comment by sebastiankb** [comment]
Daniel's PR was merged. This issue will be closed.
